-- Ad-hoc terminals: a session on a machine, with no project behind it.
--
-- A session used to require a workspace — you couldn't get a plain shell on a
-- box without first cloning or opening a repo there. But the node only needs a
-- *directory* to start a session, not a git checkout, so an ad-hoc terminal is
-- just a session with no workspace, run in the node's home directory.
--
-- Nulling the column is the honest model. The alternative — a fake "scratch"
-- workspace per node — would pollute the workspace list and get re-scanned by
-- discovery as if it were a repo.
ALTER TABLE sessions ALTER COLUMN workspace_id DROP NOT NULL;
