//! All runtime configuration comes from the environment (.env in dev).
//! No configuration value may name a specific auth provider — the OIDC issuer
//! is whatever the deployment points at.

use anyhow::{Context, Result};

/// 25 MiB, the shipped upload cap (MAIN-532 AC-6).
pub const DEFAULT_USER_CONTENT_MAX_BYTES: u64 = 25 * 1024 * 1024;

/// The SMTP receiver's default message cap — the webhook route's 25 MiB, so
/// the same message is accepted or refused whichever door it arrives at.
pub const DEFAULT_EMAIL_SMTP_MAX_BYTES: usize = 25 * 1024 * 1024;

#[derive(Debug, Clone)]
pub struct Config {
    pub app_env: String,
    pub bind: String,
    /// How long, in seconds, in-flight requests get to finish after a shutdown
    /// signal before the process exits anyway. Bounds the graceful drain so one
    /// stuck connection cannot hold the pod past Kubernetes' own grace period
    /// (`terminationGracePeriodSeconds`) and earn a SIGKILL mid-request. Set a
    /// touch below that value; defaults to 25s.
    pub shutdown_grace_secs: u64,
    pub public_base_url: String,
    pub web_origin: String,
    pub database_url: String,

    pub oidc_issuer_url: Option<String>,
    pub oidc_client_id: Option<String>,
    /// A second, PUBLIC client registered at the IdP for native apps.
    ///
    /// The control plane's own client is confidential — it holds a secret, and
    /// a secret shipped inside a desktop binary is not a secret. Native
    /// clients need their own public client, which is what the device
    /// authorization grant expects anyway.
    pub oidc_device_client_id: Option<String>,
    /// Where native clients start a device authorization.
    ///
    /// This belongs in the IdP's discovery document, and a compliant client
    /// would find it there. Two things make it configuration instead: the
    /// `openidconnect` crate's `CoreProviderMetadata` drops unrecognised
    /// fields, and providers that support the grant do not always advertise
    /// the endpoint — auth.hein.network lists `device_code` under
    /// `grant_types_supported` while omitting `device_authorization_endpoint`,
    /// so nothing can discover it. Setting it here unblocks that; fixing the
    /// discovery document is the better repair.
    pub oidc_device_authorization_endpoint: Option<String>,
    pub oidc_client_secret: Option<String>,
    pub oidc_redirect_url: Option<String>,
    pub oidc_scopes: String,

    pub session_secret: String,
    pub session_ttl_hours: i64,
    pub default_tenant_name: String,
    pub auth_dev_mode: bool,

    pub dev_join_token: Option<String>,

    /// A join token for a LOCAL install's own bundled node (MAIN-398).
    ///
    /// Seeded exactly like `dev_join_token` and deliberately NOT the same
    /// variable. That one also gates the dogfood workspace, the dev identity
    /// and `loops.enabled` — scaffolding for the compose stack that would be
    /// wrong on somebody's laptop: a workspace pointing at a repo that is not
    /// there, and loops running by surprise.
    ///
    /// It exists because a desktop install has no user yet on first run, and
    /// minting a token through `POST /nodes/join-tokens` needs one. The value
    /// is generated by the shell, kept in its app-data directory, and handed to
    /// both processes — nothing is shown to or typed by the person.
    pub local_join_token: Option<String>,

    /// Where node binaries live, served at `/dist/<artifact>`. The control
    /// image drops the build it was compiled with here.
    pub dist_dir: String,

    /// `owner/repo` whose tagged releases carry the node binaries.
    ///
    /// The control plane used to host them itself. That was the wrong call: it
    /// could only ever serve what its own build host could compile (no macOS),
    /// and it made every deployment a binary mirror. Releases are a release
    /// problem, so they live with the tags.
    pub releases_repo: String,

    /// Where the node agent connects, separate from the browser/API port.
    ///
    /// Two reasons they are split. The agent connection is the one that will
    /// carry mutual TLS: its handshake has to terminate at the control plane
    /// (only it can pick the right tenant CA), which means the edge proxy must
    /// pass it through rather than terminate it — a different rule than the
    /// browser API wants. And it keeps a machine credential and a browser
    /// session on separate doors, so a proxy misconfiguration on one cannot
    /// quietly widen the other.
    pub agent_bind: String,
    /// Public URL of the agent listener, handed to joining machines.
    ///
    /// Defaults to the API's public URL, which is right for a single-host
    /// deployment where both are the same name. Set it when the agent port has
    /// its own hostname — a proxy that terminates TLS breaks mutual auth, so
    /// that name usually resolves somewhere different on purpose.
    pub agent_public_url: Option<String>,

    /// The HTTP API's canonical public URL (MAIN-465) — what a headless run's
    /// `nook` CLI is told to dial and report. Deliberately its OWN setting:
    /// `agent_public_url` above is the mTLS agent listener, which resolves
    /// somewhere different on purpose, and `public_base_url` is the browser
    /// URL, wrong from inside a container on a dev stack. `None` means the
    /// deployment advertises nothing and runs fall back to the executor
    /// node's own configured server address.
    pub public_api_url: Option<String>,

    /// PEM certificate the agent listener serves, when the control plane
    /// terminates TLS itself. Its SHA-256 goes into join tokens so a machine
    /// can pin the server on first contact instead of trusting whatever the
    /// web PKI vouches for — any public CA can issue for any hostname, so root
    /// -store validation alone would not stop a mis-issued certificate.
    pub agent_tls_cert: Option<String>,
    /// Private key for `agent_tls_cert`. Both must be set for the agent
    /// listener to terminate TLS; either alone is a misconfiguration.
    pub agent_tls_key: Option<String>,

    // ── Artifact storage ────────────────────────────────────────────────
    /// `disk` (default) or `s3`. See `crate::storage`.
    pub artifact_store: String,
    /// Key prefix inside the bucket, so NookOS can share a bucket with
    /// whatever else the operator keeps there.
    pub artifact_prefix: String,
    /// Hand out a time-limited URL to the object store instead of streaming
    /// the bytes through this server. Faster, but exposes the store's hostname
    /// to whoever is installing — off by default so one hostname serves
    /// everything.
    pub artifact_redirect: bool,

    // ── User content ────────────────────────────────────────────────────
    /// Key prefix for what PEOPLE upload, kept apart from the distributed
    /// binaries so the two can never collide in one bucket (MAIN-532).
    pub user_content_prefix: String,
    /// Where an upload's bytes land when the store is `disk`, and the reason
    /// this is not `dist_dir` (MAIN-598).
    ///
    /// `dist_dir` is inside the image: baked read-only at build time with the
    /// release binaries, owned by root, and mounted by nothing. Writing user
    /// content there failed on every disk-backed deployment. These are two
    /// different lifetimes — one is built with the image, the other outlives
    /// it — so they are two different directories.
    ///
    /// The default is a per-user data directory, because the property that
    /// matters is that an ordinary non-root user can write it with nothing
    /// pre-created and nothing configured. A deployment that wants the bytes
    /// to survive the container says so with this variable.
    pub user_content_dir: String,
    /// `artifact_redirect`'s twin for user content, and deliberately its own
    /// variable: binaries are fetched by a machine mid-install, uploads by a
    /// signed-in browser, and a deployment can reasonably want redirection for
    /// one and not the other.
    pub user_content_redirect: bool,
    /// Largest single upload accepted, in bytes. 25 MiB by default.
    pub user_content_max_bytes: u64,

    pub s3_bucket: Option<String>,
    /// Unset for AWS; set for MinIO or GCS.
    pub s3_endpoint: Option<String>,
    pub s3_region: Option<String>,
    pub s3_access_key_id: Option<String>,
    pub s3_secret_access_key: Option<String>,
    /// Path-style addressing (`host/bucket/key`). Default true, because
    /// self-hosted gateways rarely have per-bucket DNS.
    pub s3_path_style: bool,

    // ── Cache provider ──────────────────────────────────────────────────
    /// Which cache backend to use, chosen by name — `memory` (default) or the
    /// reserved-but-unbuilt `redis`. Explicit, like `NOOK_ARTIFACT_STORE`: a
    /// cache is a deployment decision, and a hosted redis later means a new
    /// name here, not inference. See `crate::cache`.
    pub cache_provider: String,

    // ── Queue provider ──────────────────────────────────────────────────
    /// Which durable-work-queue backend to use, chosen by name — `database`
    /// (default), `redis` or `sqs`, all three implemented (MAIN-412 corrected
    /// this line, which still called the last two unbuilt). Explicit, like the
    /// cache: a queue is a deployment decision, and a hosted broker later means
    /// a new name here, not inference. See `crate::queue`.
    pub queue_provider: String,
    /// `NOOK_REDIS_URL` — the Redis connection for the redis queue provider (and
    /// the future redis cache). Required when `queue_provider = redis`.
    pub redis_url: Option<String>,

    // ── SQS queue provider ──────────────────────────────────────────────
    /// `NOOK_SQS_QUEUE_URL` — the main SQS queue's URL. Required when
    /// `queue_provider = sqs`. Credentials come from the standard AWS chain
    /// (`AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY`, instance role, …).
    pub sqs_queue_url: Option<String>,
    /// `NOOK_SQS_DLQ_URL` — an optional dead-letter queue. When set, an explicit
    /// `Nack::Dead` (and an app-level attempt-cap exhaustion) sends the message
    /// here with its reason; when unset those messages are simply deleted. SQS's
    /// own redrive policy (operator-configured on the main queue, NG-1) is the
    /// backstop and is documented, not created by us.
    pub sqs_dlq_url: Option<String>,
    /// `NOOK_SQS_ENDPOINT_URL` — override the SQS endpoint, for an emulator
    /// (ElasticMQ/LocalStack) or a VPC endpoint. Unset uses the real AWS URL.
    pub sqs_endpoint_url: Option<String>,
    /// `NOOK_SQS_REGION` — the AWS region for SQS. Defaults to `us-east-1`.
    pub sqs_region: Option<String>,

    // ── Email (mail provider) ───────────────────────────────────────────
    /// Which mail transport to use, chosen by name — `smtp` or `capture`.
    /// Explicit, like `NOOK_ARTIFACT_STORE`, rather than inferred from whether
    /// an SMTP host happens to be set: a provider is a deployment decision, and
    /// adding a hosted transport later (SES, Sendgrid, …) means a new name here,
    /// not new inference. Defaults to `capture` (logs, does not send).
    pub mail_provider: String,
    /// SMTP host, used when `mail_provider = smtp`. Dev points at Mailpit, prod
    /// at the mail relay.
    pub smtp_host: Option<String>,
    /// SMTP port. 587 (submission/STARTTLS) by default; 1025 for Mailpit, 465
    /// for implicit TLS.
    pub smtp_port: u16,
    /// Transport security: `starttls` (default), `implicit` (TLS from the
    /// first byte, port 465), or `none` (plaintext, for Mailpit).
    pub smtp_tls: String,
    /// The envelope/from address, e.g. `NookOS <no-reply@example.com>`.
    pub smtp_from: String,
    /// Optional SMTP auth. Both set → credentials are sent; Mailpit needs none.
    pub smtp_username: Option<String>,
    pub smtp_password: Option<String>,

    // ── Inbound email ───────────────────────────────────────────────────
    /// Shared secret the inbound-email webhook's HMAC is verified against
    /// (MAIN-329). `None` — the shipped default — means the deployment receives
    /// no mail: `POST /api/v1/email/inbound` answers 404 and nothing is parsed.
    ///
    /// Deployment-scoped rather than tenant-scoped, and that is what fixes the
    /// ORDER of the trust gate. The route takes no principal and no path
    /// parameter, so a per-tenant secret could only be found by parsing the
    /// body first — verifying a signature with a key the unverified payload
    /// chose. One relay, one secret, verified against the raw bytes before
    /// anything reads them; which tenant the mail belongs to is decided
    /// afterwards, from the recipient.
    pub email_inbound_secret: Option<String>,

    /// Where the direct SMTP receiver listens, e.g. `0.0.0.0:2525` (MAIN-334).
    /// `None` — the shipped default — means no listener is opened at all: this
    /// is the only source that binds a port, so it is off until an operator
    /// names an address.
    pub email_smtp_listen: Option<String>,
    /// The credential the relay in front must present. BOTH are required
    /// whenever the listener is enabled, and the process refuses to boot
    /// otherwise: an SMTP port that accepts unauthenticated transactions
    /// accepts any envelope sender, and the support-staff allow-list is then a
    /// comparison against a string the sender chose.
    pub email_smtp_username: Option<String>,
    pub email_smtp_password: Option<String>,
    /// Implicit TLS for the receiver (the SMTPS shape, as on port 465). Both
    /// set → the socket is wrapped before the greeting; both unset → the
    /// listener is plaintext and must sit on a trusted network. Half-set is a
    /// boot failure, exactly as the agent listener's pair is.
    pub email_smtp_tls_cert: Option<String>,
    pub email_smtp_tls_key: Option<String>,
    /// The `authserv-id` the front MTA stamps its `Authentication-Results`
    /// under — the name in the header, before the first `;`. Set it and a
    /// verdict reported by anything else is refused; leave it unset and the
    /// topmost header is trusted on position alone, which is the weaker rule
    /// `email_inbound::require_verified_sender` explains.
    pub email_smtp_authserv_id: Option<String>,
    /// The largest message the receiver accepts, advertised as ESMTP `SIZE`
    /// and enforced while `DATA` is being read. Matches the webhook route's
    /// limit, because the pipeline below both is the same.
    pub email_smtp_max_bytes: usize,

    // ── Postmark (HTTP mail provider) ───────────────────────────────────
    /// Server token for `mail_provider = postmark`, sent as the
    /// `X-Postmark-Server-Token` header. Missing → the provider fails to build
    /// and falls back to capture (nothing is delivered), never a panic.
    pub postmark_token: Option<String>,
    /// Postmark's send endpoint. Overridable so tests can point it at a mock.
    pub postmark_api_url: String,
    /// The verified sender used by the Postmark provider, e.g.
    /// `NookOS <no-reply@hein.network>`. Separate from `smtp_from` because the
    /// verified sender at Postmark need not match the SMTP relay's envelope.
    pub mail_from: String,

    // ── Send guards (provider-agnostic) ─────────────────────────────────
    /// GLOBAL send switch. Default OFF: unless this is true, EVERY provider —
    /// including a fully-configured postmark/smtp — captures (logs "would
    /// send"), delivering nothing. Turning sending on is a deliberate ops step.
    pub mail_send_enabled: bool,
    /// Whether `notification`-category mail (the email notification channel) may
    /// send. Default OFF: even with `mail_send_enabled`, notifications stay
    /// captured until this is separately turned on. Transactional mail
    /// (verification, invites) is unaffected by this flag.
    pub mail_notifications_enabled: bool,
    /// Hard monthly cap on REAL sends — a backstop against exhausting the
    /// Postmark allowance. At the cap, further sends are captured (WARN), not
    /// sent. Counted from recorded sends, so it survives restarts. Defaults to
    /// 100 (the Postmark free allowance); `0` blocks all real sends.
    pub mail_max_per_month: Option<i64>,
    /// Optional daily cap, same semantics as the monthly one. Unset by default.
    pub mail_max_per_day: Option<i64>,

    // ── Giphy (chat GIFs, MAIN-171) ─────────────────────────────────────
    /// Giphy API key, from `NOOK_GIPHY_KEY`. Unset — the shipped default, and
    /// the only state an open-source deployment has until its operator brings
    /// their own key — means chat's GIF button is not rendered at all. Nothing
    /// else changes: the emoji picker and every other composer affordance work
    /// exactly as they do with a key set.
    ///
    /// This is a browser-side key by Giphy's own design (their web SDK embeds
    /// one), so `/api/v1/config` hands it to a signed-in client rather than
    /// proxying searches through here.
    pub giphy_key: Option<String>,

    // ── Trusted reverse proxies ─────────────────────────────────────────
    /// CIDRs whose `X-Forwarded-For` header we believe. Empty by default, which
    /// means NO proxy is trusted and the peer socket IP is always the client —
    /// the safe default, because an attacker who can set XFF must not be able to
    /// spoof their source for the per-IP rate limiter. Set `NOOK_TRUSTED_PROXIES`
    /// (comma-separated CIDRs) to the edge proxy's address range when one fronts
    /// this service. Resolved by nook-control's client-IP helper.
    pub trusted_proxies: Vec<ipnet::IpNet>,

    // ── Loop jobs ───────────────────────────────────────────────────────
    /// How many seconds an executor node may be unseen (`nodes.last_seen_at`)
    /// before the reaper fails a job it was running (MAIN-164), so a dead
    /// operator container cannot strand work forever. Default 180.
    pub job_reap_grace_secs: u64,
    /// How many seconds a job may sit `queued` with an UNCHANGED
    /// `queued_reason` before the reaper cancels it and escalates to a human
    /// (MAIN-496). Measured from the last time the reason changed, not from
    /// creation: a job whose reason keeps moving is making progress toward
    /// placement and is never escalated. Default 1800 (30 minutes) — long
    /// enough to outlast a node restart or an operator upgrade, short enough
    /// that a starved card surfaces within the hour instead of never.
    pub job_starve_secs: u64,
    /// How many seconds a `claimed`/`running` job may go without a single new
    /// transcript entry before the reaper treats it as orphaned and fails it
    /// (MAIN-506). Measured on the JOB's own progress, not the node's liveness,
    /// because the case this catches is an executor agent that restarted:
    /// the node is healthy and heartbeating, so `job_reap_grace_secs` never
    /// trips, while the run itself has stopped producing output forever.
    ///
    /// Default 3600 (1 hour), deliberately far longer than the starvation
    /// window: a streaming run emits a transcript entry per assistant message
    /// and per tool call, but ONE tool call can legitimately be a full test
    /// suite, so the threshold has to outlast the longest single command a
    /// build might run. `waiting_on_human` is exempt — a paused run makes no
    /// progress by design.
    pub job_stall_secs: u64,

    // ── Board-card claim leases (MAIN-229) ──────────────────────────────
    /// How many seconds a card's bound session's node may be unseen before the
    /// claim reaper treats the worker as gone and requeues the card. Shorter
    /// than `job_reap_grace_secs` because a board card is cheap to requeue and
    /// nothing is lost by doing it early. Default 120.
    pub claim_session_grace_secs: u64,
    /// The hard backstop: how long an agent claim may hold a card before the
    /// reaper escalates it to a human. Not a kill switch — a card past this cap
    /// with a live session is labelled and notified, never moved. Default 14400
    /// (4 hours).
    pub max_claim_secs: u64,
    /// How often the claim reaper scans. Default 30.
    pub claim_reap_scan_secs: u64,

    // ── Merged-PR board reconciliation (MAIN-491) ───────────────────────
    /// How often the merge sweep asks the forge how each in-flight card's pull
    /// request ended. Slower than the claim reaper because the answer changes
    /// only when somebody merges, and each pass costs real GitHub calls —
    /// but fast enough that the board stops lying within minutes rather than
    /// waiting for whenever an agent skill next runs. Default 120.
    pub merge_reconcile_scan_secs: u64,

    // ── Tunnels (MAIN-9) ────────────────────────────────────────────────
    /// The wildcard zone tunnels are served under, e.g. `nook.hein.network`.
    /// A request whose `Host` is a subdomain of this is a tunnel and is answered
    /// by the tunnel surface instead of the API (MAIN-403 AC-1).
    ///
    /// `None` — the shipped default — turns the whole surface off: host dispatch
    /// never runs and no host is treated as a tunnel. Deliberately not guessed
    /// from `public_base_url`, because serving `*.<domain>` needs a wildcard DNS
    /// record and a certificate for it, and inferring the name would produce a
    /// tunnel that resolves nowhere.
    pub tunnel_domain: Option<String>,

    /// How many seconds a tunnel may go unused before the sweep tears it down
    /// (MAIN-404 AC-3). A tunnel costs nothing to re-open and holds a port on
    /// somebody's machine open to the whole tenant while it exists, so the
    /// default is a window rather than forever. Default 1800 (30 minutes);
    /// `0` disables the sweep, which is a deliberate choice an operator can
    /// make and never one they get by leaving the variable out.
    pub tunnel_idle_secs: u64,

    // ── Workspace discovery ─────────────────────────────────────────────
    /// How many seconds a checkout may stay tombstoned (`node_workspaces
    /// .missing_at`) before the retention sweep hard-deletes it (MAIN-220). A
    /// node that stops reporting a checkout no longer erases it immediately;
    /// the row is marked missing and only reaped after this window, so a
    /// transient unmount or a moved directory heals with its id intact. Default
    /// 604800 (7 days).
    pub workspace_missing_retention_secs: u64,
}

/// Parse one entry of `NOOK_TRUSTED_PROXIES`: a CIDR (`10.0.0.0/8`) or a bare
/// address (`10.0.0.5`, taken as a single host). Unparseable entries are
/// dropped rather than failing the boot — a typo in one proxy must not take the
/// whole service down, and a dropped entry only ever narrows what we trust.
fn parse_trusted_proxy(s: &str) -> Option<ipnet::IpNet> {
    let s = s.trim();
    if s.is_empty() {
        return None;
    }
    s.parse::<ipnet::IpNet>()
        .ok()
        .or_else(|| s.parse::<std::net::IpAddr>().ok().map(ipnet::IpNet::from))
}

fn env_opt(key: &str) -> Option<String> {
    std::env::var(key).ok().filter(|v| !v.trim().is_empty())
}

/// `$XDG_DATA_HOME/nook/user-content`, or `~/.local/share/nook/user-content`
/// (MAIN-598).
///
/// The one requirement is that an ordinary non-root user can write it having
/// created nothing and configured nothing — so a plain binary, or a desktop /
/// SQLite standalone install, accepts an upload out of the box. A path under
/// `/var/lib` or `/usr/local/share` reads more like a server, and is exactly
/// the class of path this card exists because of: not writable by the process
/// that has to write it.
///
/// The temp-dir last resort is for a container run as a bare numeric uid with
/// no passwd entry, where `HOME` is unset. It is writable and it is ephemeral;
/// the deployments that must keep the bytes set `NOOK_USER_CONTENT_DIR`
/// explicitly (docker-compose and the Helm chart both do).
fn default_user_content_dir() -> String {
    user_content_dir_from(
        env_opt("XDG_DATA_HOME"),
        env_opt("HOME"),
        std::env::temp_dir(),
    )
}

/// The path-derivation alone, taking its inputs by value so the test can pin the
/// LOGIC without touching the process environment.
///
/// It used to read the env directly, so the test drove it through the ambient
/// `HOME`. In a container run as a bare uid with `HOME=/` (root-owned, mode
/// 755) the default was `/.local/share/nook/user-content` — a real, correct
/// answer for that odd env, but not writable, so the test failed there and only
/// there. That is not a Postgres/SQLite difference; it surfaced on whichever leg
/// happened to run under that HOME (MAIN-6xx). Made pure so the test supplies a
/// normal HOME and never depends on the one it inherits.
fn user_content_dir_from(
    xdg_data_home: Option<String>,
    home: Option<String>,
    temp_dir: std::path::PathBuf,
) -> String {
    let base = xdg_data_home
        .map(std::path::PathBuf::from)
        .or_else(|| home.map(|h| std::path::PathBuf::from(h).join(".local/share")))
        .unwrap_or(temp_dir);
    base.join("nook/user-content")
        .to_string_lossy()
        .into_owned()
}

/// The three states an OIDC configuration can be in at boot, which is one more
/// than [`Config::oidc_configured`] can express — and the missing one is the
/// only state an operator can be in by mistake.
#[derive(Debug, PartialEq, Eq)]
pub enum OidcSetup<'a> {
    /// Everything an authorization-code login needs is set: discover.
    Configured { issuer: &'a str },
    /// An issuer is set but the set is incomplete. Unfinished intent, not a
    /// local install — startup WARNs and names `missing` (MAIN-527 AC-1).
    Partial {
        issuer: &'a str,
        missing: Vec<&'static str>,
    },
    /// No issuer at all: the local install, where the absence is the expected
    /// state and startup says so at INFO (MAIN-397 AC-3).
    Absent,
}

impl Config {
    pub fn from_env() -> Result<Self> {
        let cfg = Self {
            app_env: env_opt("APP_ENV").unwrap_or_else(|| "dev".into()),
            bind: env_opt("CONTROL_PLANE_BIND").unwrap_or_else(|| "0.0.0.0:8080".into()),
            shutdown_grace_secs: env_opt("NOOK_SHUTDOWN_GRACE_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(25),
            public_base_url: env_opt("PUBLIC_BASE_URL")
                .unwrap_or_else(|| "http://localhost:8080".into()),
            web_origin: env_opt("WEB_ORIGIN").unwrap_or_else(|| "http://localhost:5173".into()),
            database_url: env_opt("DATABASE_URL").context("DATABASE_URL is required")?,

            oidc_issuer_url: env_opt("OIDC_ISSUER_URL"),
            oidc_client_id: env_opt("OIDC_CLIENT_ID"),
            oidc_device_client_id: env_opt("OIDC_DEVICE_CLIENT_ID"),
            oidc_device_authorization_endpoint: env_opt("OIDC_DEVICE_AUTHORIZATION_ENDPOINT"),
            oidc_client_secret: env_opt("OIDC_CLIENT_SECRET"),
            oidc_redirect_url: env_opt("OIDC_REDIRECT_URL"),
            oidc_scopes: env_opt("OIDC_SCOPES").unwrap_or_else(|| "openid profile email".into()),

            session_secret: env_opt("SESSION_SECRET").context("SESSION_SECRET is required")?,
            session_ttl_hours: env_opt("SESSION_TTL_HOURS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(168),
            default_tenant_name: env_opt("DEFAULT_TENANT_NAME").unwrap_or_else(|| "dev".into()),
            auth_dev_mode: env_opt("AUTH_DEV_MODE")
                .map(|v| v == "true" || v == "1")
                .unwrap_or(false),

            releases_repo: env_opt("NOOK_RELEASES_REPO")
                .unwrap_or_else(|| "nook-os/nook-os".into()),
            agent_tls_cert: env_opt("NOOK_AGENT_TLS_CERT"),
            agent_tls_key: env_opt("NOOK_AGENT_TLS_KEY"),
            agent_bind: env_opt("NOOK_AGENT_BIND").unwrap_or_else(|| "0.0.0.0:8081".into()),
            agent_public_url: env_opt("NOOK_AGENT_PUBLIC_URL"),
            public_api_url: env_opt("NOOK_PUBLIC_API_URL"),
            dist_dir: env_opt("NOOK_DIST_DIR")
                .unwrap_or_else(|| "/usr/local/share/nook/dist".into()),

            artifact_store: env_opt("NOOK_ARTIFACT_STORE").unwrap_or_else(|| "disk".into()),
            artifact_prefix: env_opt("NOOK_ARTIFACT_PREFIX").unwrap_or_else(|| "nook".into()),
            artifact_redirect: env_opt("NOOK_ARTIFACT_REDIRECT")
                .map(|v| v == "true" || v == "1")
                .unwrap_or(false),
            user_content_prefix: env_opt("NOOK_USER_CONTENT_PREFIX")
                .unwrap_or_else(|| "nook/user-content".into()),
            user_content_dir: env_opt("NOOK_USER_CONTENT_DIR")
                .unwrap_or_else(default_user_content_dir),
            user_content_redirect: env_opt("NOOK_USER_CONTENT_REDIRECT")
                .map(|v| v == "true" || v == "1")
                .unwrap_or(false),
            // A value that does not parse falls back to the default rather than
            // to zero, which would refuse every upload.
            user_content_max_bytes: env_opt("NOOK_USER_CONTENT_MAX_BYTES")
                .and_then(|v| v.trim().parse::<u64>().ok())
                .unwrap_or(DEFAULT_USER_CONTENT_MAX_BYTES),
            s3_bucket: env_opt("NOOK_S3_BUCKET"),
            s3_endpoint: env_opt("NOOK_S3_ENDPOINT"),
            s3_region: env_opt("NOOK_S3_REGION"),
            s3_access_key_id: env_opt("NOOK_S3_ACCESS_KEY_ID"),
            s3_secret_access_key: env_opt("NOOK_S3_SECRET_ACCESS_KEY"),
            s3_path_style: env_opt("NOOK_S3_PATH_STYLE")
                .map(|v| v == "true" || v == "1")
                .unwrap_or(true),
            dev_join_token: env_opt("NOOK_DEV_JOIN_TOKEN"),
            local_join_token: env_opt("NOOK_LOCAL_JOIN_TOKEN"),

            cache_provider: env_opt("NOOK_CACHE_PROVIDER").unwrap_or_else(|| "memory".into()),

            queue_provider: env_opt("NOOK_QUEUE_PROVIDER").unwrap_or_else(|| "database".into()),
            redis_url: env_opt("NOOK_REDIS_URL"),
            sqs_queue_url: env_opt("NOOK_SQS_QUEUE_URL"),
            sqs_dlq_url: env_opt("NOOK_SQS_DLQ_URL"),
            sqs_endpoint_url: env_opt("NOOK_SQS_ENDPOINT_URL"),
            sqs_region: env_opt("NOOK_SQS_REGION"),

            mail_provider: env_opt("MAIL_PROVIDER").unwrap_or_else(|| "capture".into()),
            smtp_host: env_opt("SMTP_HOST"),
            smtp_port: env_opt("SMTP_PORT")
                .and_then(|v| v.parse().ok())
                .unwrap_or(587),
            smtp_tls: env_opt("SMTP_TLS").unwrap_or_else(|| "starttls".into()),
            smtp_from: env_opt("SMTP_FROM").unwrap_or_else(|| "NookOS <no-reply@localhost>".into()),
            smtp_username: env_opt("SMTP_USERNAME"),
            smtp_password: env_opt("SMTP_PASSWORD"),

            email_inbound_secret: env_opt("EMAIL_INBOUND_SECRET"),
            email_smtp_listen: env_opt("EMAIL_SMTP_LISTEN"),
            email_smtp_username: env_opt("EMAIL_SMTP_USERNAME"),
            email_smtp_password: env_opt("EMAIL_SMTP_PASSWORD"),
            email_smtp_tls_cert: env_opt("EMAIL_SMTP_TLS_CERT"),
            email_smtp_tls_key: env_opt("EMAIL_SMTP_TLS_KEY"),
            email_smtp_authserv_id: env_opt("EMAIL_SMTP_AUTHSERV_ID"),
            email_smtp_max_bytes: env_opt("EMAIL_SMTP_MAX_BYTES")
                .and_then(|v| v.parse().ok())
                .unwrap_or(DEFAULT_EMAIL_SMTP_MAX_BYTES),

            postmark_token: env_opt("POSTMARK_TOKEN"),
            postmark_api_url: env_opt("POSTMARK_API_URL")
                .unwrap_or_else(|| "https://api.postmarkapp.com/email".into()),
            mail_from: env_opt("MAIL_FROM").unwrap_or_else(|| "NookOS <no-reply@localhost>".into()),

            mail_send_enabled: env_opt("MAIL_SEND_ENABLED")
                .map(|v| v == "true" || v == "1")
                .unwrap_or(false),
            mail_notifications_enabled: env_opt("MAIL_NOTIFICATIONS_ENABLED")
                .map(|v| v == "true" || v == "1")
                .unwrap_or(false),
            // Always a monthly cap; unset or unparseable falls back to 100 (the
            // Postmark free allowance) so a typo can never silently uncap sends.
            mail_max_per_month: Some(
                env_opt("MAIL_MAX_PER_MONTH")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(100),
            ),
            mail_max_per_day: env_opt("MAIL_MAX_PER_DAY").and_then(|v| v.parse().ok()),

            giphy_key: env_opt("NOOK_GIPHY_KEY"),

            // No proxy is trusted unless named, so XFF is ignored by default.
            trusted_proxies: env_opt("NOOK_TRUSTED_PROXIES")
                .map(|v| v.split(',').filter_map(parse_trusted_proxy).collect())
                .unwrap_or_default(),

            job_reap_grace_secs: env_opt("NOOK_JOB_REAP_GRACE_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(180),
            job_starve_secs: env_opt("NOOK_JOB_STARVE_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(1_800),
            job_stall_secs: env_opt("NOOK_JOB_STALL_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(3_600),

            claim_session_grace_secs: env_opt("NOOK_CLAIM_SESSION_GRACE_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(120),
            max_claim_secs: env_opt("NOOK_MAX_CLAIM_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(14_400),
            claim_reap_scan_secs: env_opt("NOOK_CLAIM_REAP_SCAN_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(30),
            merge_reconcile_scan_secs: env_opt("NOOK_MERGE_RECONCILE_SCAN_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(120),

            // Normalised once, here: a leading dot and a trailing dot are both
            // ways people write a zone, and host matching compares lowercase
            // ASCII. Doing it at the edge means every reader compares like with
            // like instead of re-normalising and drifting.
            tunnel_domain: env_opt("TUNNEL_DOMAIN")
                .map(|d| d.trim().trim_matches('.').to_ascii_lowercase()),
            tunnel_idle_secs: env_opt("TUNNEL_IDLE_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(1800),

            workspace_missing_retention_secs: env_opt("NOOK_WORKSPACE_MISSING_RETENTION_SECS")
                .and_then(|v| v.parse().ok())
                .unwrap_or(604_800),
        };

        if cfg.is_production() && cfg.auth_dev_mode {
            anyhow::bail!("AUTH_DEV_MODE must not be enabled when APP_ENV=production");
        }
        // The cache provider is selected the same way; an unknown name is a
        // misconfiguration worth stopping for.
        crate::cache::validate_provider(&cfg.cache_provider)?;
        // Same story for the queue: an unknown NAME is refused at boot rather
        // than silently draining a single-node table a deployment believed was
        // a shared broker. All three known names are implemented, so this now
        // catches typos rather than unbuilt providers.
        crate::queue::validate_provider(&cfg.queue_provider)?;
        // Either selecting `redis` needs a present, parseable NOOK_REDIS_URL —
        // refuse boot on a missing/malformed one rather than silently falling
        // back to the local backend.
        check_redis_url(
            cfg.queue_provider == "redis",
            "NOOK_QUEUE_PROVIDER",
            cfg.redis_url.as_deref(),
        )?;
        check_redis_url(
            cfg.cache_provider == "redis",
            "NOOK_CACHE_PROVIDER",
            cfg.redis_url.as_deref(),
        )?;
        // The sqs queue needs a queue URL; a missing one refuses boot here (the
        // sync half of AC-3). The async reachability probe is in
        // `queue::sqs::SqsQueue::from_config`, run at boot.
        if cfg.queue_provider == "sqs"
            && cfg
                .sqs_queue_url
                .as_deref()
                .filter(|u| !u.is_empty())
                .is_none()
        {
            anyhow::bail!(
                "NOOK_QUEUE_PROVIDER=sqs requires NOOK_SQS_QUEUE_URL to be set (the SQS queue URL)"
            );
        }
        // An unknown mail provider is a misconfiguration worth stopping for,
        // rather than silently falling through to some default and dropping mail.
        if !crate::mailer::is_known_provider(&cfg.mail_provider) {
            anyhow::bail!(
                "MAIL_PROVIDER must be one of [{}] — got {:?}",
                crate::mailer::PROVIDERS.join(", "),
                cfg.mail_provider
            );
        }
        if cfg.session_secret.len() < 32 {
            anyhow::bail!("SESSION_SECRET must be at least 32 characters");
        }
        Ok(cfg)
    }

    pub fn is_production(&self) -> bool {
        self.app_env == "production"
    }

    pub fn oidc_configured(&self) -> bool {
        matches!(self.oidc_setup(), OidcSetup::Configured { .. })
    }

    /// How complete this instance's identity-provider configuration is.
    ///
    /// The distinction that matters at boot is between an operator who set
    /// nothing and one who set some of it: `oidc_configured()` collapses both
    /// into "not configured", which is what made a half-configured provider
    /// report as the deliberate local case (MAIN-527).
    pub fn oidc_setup(&self) -> OidcSetup<'_> {
        let Some(issuer) = self.oidc_issuer_url.as_deref() else {
            return OidcSetup::Absent;
        };
        let missing: Vec<&'static str> = [
            ("OIDC_CLIENT_ID", self.oidc_client_id.is_some()),
            ("OIDC_REDIRECT_URL", self.oidc_redirect_url.is_some()),
        ]
        .into_iter()
        .filter_map(|(name, present)| (!present).then_some(name))
        .collect();
        if missing.is_empty() {
            OidcSetup::Configured { issuer }
        } else {
            OidcSetup::Partial { issuer, missing }
        }
    }

    /// A Config with everything defaulted, for unit tests that need one without
    /// touching the process environment. Mirrors the `from_env` defaults.
    ///
    /// Compiled for this crate's own tests and, via the `test-support` feature,
    /// for downstream crates' tests (nook-control enables it as a dev-dep) —
    /// the split in MAIN-146 moved this out of nook-control, so its tests can no
    /// longer reach a `#[cfg(test)]`-only helper here.
    #[cfg(any(test, feature = "test-support"))]
    pub fn for_test() -> Self {
        Self {
            app_env: "test".into(),
            bind: "127.0.0.1:0".into(),
            shutdown_grace_secs: 25,
            public_base_url: "http://localhost:8080".into(),
            web_origin: "http://localhost:5173".into(),
            database_url: String::new(),
            oidc_issuer_url: None,
            oidc_client_id: None,
            oidc_device_client_id: None,
            oidc_device_authorization_endpoint: None,
            oidc_client_secret: None,
            oidc_redirect_url: None,
            oidc_scopes: "openid profile email".into(),
            session_secret: "0".repeat(64),
            session_ttl_hours: 168,
            default_tenant_name: "test".into(),
            auth_dev_mode: true,
            dev_join_token: None,
            local_join_token: None,
            dist_dir: "/tmp".into(),
            releases_repo: "nook-os/nook-os".into(),
            agent_bind: "127.0.0.1:0".into(),
            agent_public_url: None,
            public_api_url: None,
            agent_tls_cert: None,
            agent_tls_key: None,
            artifact_store: "disk".into(),
            artifact_prefix: "nook".into(),
            artifact_redirect: false,
            user_content_prefix: "nook/user-content".into(),
            // Under the temp dir rather than the caller's real data directory:
            // a test that uploads must not leave objects in `~/.local/share`.
            user_content_dir: std::env::temp_dir()
                .join("nook-test-user-content")
                .to_string_lossy()
                .into_owned(),
            user_content_redirect: false,
            user_content_max_bytes: DEFAULT_USER_CONTENT_MAX_BYTES,
            s3_bucket: None,
            s3_endpoint: None,
            s3_region: None,
            s3_access_key_id: None,
            s3_secret_access_key: None,
            s3_path_style: true,
            cache_provider: "memory".into(),
            queue_provider: "database".into(),
            redis_url: None,
            sqs_queue_url: None,
            sqs_dlq_url: None,
            sqs_endpoint_url: None,
            sqs_region: None,
            mail_provider: "capture".into(),
            smtp_host: None,
            smtp_port: 587,
            smtp_tls: "starttls".into(),
            smtp_from: "NookOS <no-reply@localhost>".into(),
            smtp_username: None,
            smtp_password: None,
            email_inbound_secret: None,
            email_smtp_listen: None,
            email_smtp_username: None,
            email_smtp_password: None,
            email_smtp_tls_cert: None,
            email_smtp_tls_key: None,
            email_smtp_authserv_id: None,
            email_smtp_max_bytes: DEFAULT_EMAIL_SMTP_MAX_BYTES,
            postmark_token: None,
            postmark_api_url: "https://api.postmarkapp.com/email".into(),
            mail_from: "NookOS <no-reply@localhost>".into(),
            // Tests get the shipped-safe defaults: sending off, notifications
            // off, a monthly cap. Guard tests set these explicitly per case.
            mail_send_enabled: false,
            mail_notifications_enabled: false,
            mail_max_per_month: Some(100),
            mail_max_per_day: None,
            giphy_key: None,
            trusted_proxies: Vec::new(),
            // Off, like a fresh deployment: a test that wants the tunnel surface
            // sets the domain itself, so nothing gets host dispatch by accident.
            tunnel_domain: None,
            tunnel_idle_secs: 1800,
            job_reap_grace_secs: 180,
            job_starve_secs: 1_800,
            job_stall_secs: 3_600,
            claim_session_grace_secs: 120,
            max_claim_secs: 14_400,
            claim_reap_scan_secs: 30,
            merge_reconcile_scan_secs: 120,
            workspace_missing_retention_secs: 604_800,
        }
    }
}

/// A component selecting the `redis` provider needs a present, **parseable**
/// `NOOK_REDIS_URL`.
///
/// A malformed URL refuses boot rather than letting `from_config` silently fall
/// back to the local backend — a silent swap would split-brain queue work
/// routing (some producers on redis, some on postgres), or hand back a
/// per-process cache someone asked to be shared, and contradicts the
/// boot-refusal principle both modules follow. `RedisClient::open` validates the
/// URL syntactically without connecting, so this is a cheap, offline check.
/// `env_name` is the selecting env var, so the error names the right knob.
fn check_redis_url(uses_redis: bool, env_name: &str, redis_url: Option<&str>) -> Result<()> {
    if !uses_redis {
        return Ok(());
    }
    let Some(url) = redis_url else {
        anyhow::bail!("{env_name}=redis requires NOOK_REDIS_URL to be set (the Redis connection)");
    };
    crate::redis_client::RedisClient::open(url)
        .with_context(|| format!("{env_name}=redis but NOOK_REDIS_URL is malformed"))?;
    Ok(())
}

/// Settings this build no longer honours, each paired with what replaced it.
///
/// Held as DATA rather than as an `if` at the boot site so the warning and the
/// replacement it names cannot drift apart, and so a test can assert every entry
/// actually says what to do instead. A retired setting that warns "this is
/// ignored" and stops there leaves an operator holding a broken deployment and a
/// search box.
pub const RETIRED_ENV: &[(&str, &str)] = &[(
    "MCP_TOKEN",
    "the static MCP token is retired (MAIN-602). /mcp now takes a personal access \
     token carrying the 'mcp' scope — mint one with `POST /api/v1/tokens` \
     {\"scopes\":[\"mcp\"]}, or from Settings → Access tokens — or an OIDC access \
     token as before. It is safe to delete MCP_TOKEN from your environment.",
)];

/// Warn about every retired setting this process still finds in its environment.
///
/// Called at boot, after the subscriber is installed. A deployment that still
/// sets one is not broken by it — the value is simply read by nobody — so this
/// is a warning and never a refusal.
pub fn warn_retired_env() {
    for (name, replacement) in RETIRED_ENV {
        if std::env::var(name).is_ok() {
            tracing::warn!(
                setting = name,
                "{name} is set but no longer does anything: {replacement}"
            );
        }
    }
}

#[cfg(test)]
mod retired_env_tests {
    use super::RETIRED_ENV;

    /// AC-5: a deployment still setting the retired variable is told what to
    /// mint instead — the whole value of the warning is the second half.
    #[test]
    fn every_retired_setting_names_its_replacement() {
        for (name, replacement) in RETIRED_ENV {
            assert!(!replacement.is_empty(), "{name} says nothing");
            assert!(
                replacement.contains("MAIN-"),
                "{name} does not name the change that retired it: {replacement}"
            );
        }
        let (_, mcp) = RETIRED_ENV
            .iter()
            .find(|(n, _)| *n == "MCP_TOKEN")
            .expect("MCP_TOKEN is retired");
        assert!(
            mcp.contains("'mcp' scope"),
            "names the scope to mint: {mcp}"
        );
    }
}

#[cfg(test)]
mod user_content_dir_tests {
    use super::user_content_dir_from;

    /// MAIN-598 AC-2: the shipped default is writable by whoever is running,
    /// with nothing pre-created and nothing configured — which is the property
    /// `/usr/local/share/nook/dist` did not have and this card exists over.
    ///
    /// It creates the directory, because that is the claim: a plain binary or a
    /// standalone install takes an upload out of the box.
    #[test]
    fn the_default_is_a_per_user_directory_this_process_can_write() {
        // A normal, writable HOME supplied by the test — never the ambient one,
        // which in a container may be `/` (root-owned) and is not what this
        // property is about. Pinning the input keeps the test independent of the
        // environment it runs in, which is why it moved off the real env.
        let home = std::env::temp_dir().join(format!("nook-uc-{}", uuid::Uuid::now_v7().simple()));
        std::fs::create_dir_all(&home).expect("a home to derive under");

        let dir = std::path::PathBuf::from(user_content_dir_from(
            None,
            Some(home.to_string_lossy().into_owned()),
            std::env::temp_dir(),
        ));
        assert!(dir.ends_with("nook/user-content"), "{}", dir.display());
        assert!(
            dir.starts_with(&home),
            "under the per-user home: {}",
            dir.display()
        );
        assert!(
            !dir.starts_with("/usr") && !dir.starts_with("/opt"),
            "never a path inside the image: {}",
            dir.display()
        );

        std::fs::create_dir_all(&dir).expect("an ordinary user can create it");
        let probe = dir.join(".write-probe");
        std::fs::write(&probe, b"writable").expect("and write in it");
        std::fs::remove_file(&probe).expect("and clean up after itself");

        // With neither var set, the last resort is the temp dir — also writable,
        // which is the whole point of the fallback (a bare-uid container).
        let fallback =
            std::path::PathBuf::from(user_content_dir_from(None, None, std::env::temp_dir()));
        assert!(
            fallback.starts_with(std::env::temp_dir()),
            "{}",
            fallback.display()
        );

        let _ = std::fs::remove_dir_all(&home);
    }
}

#[cfg(test)]
mod queue_config_tests {
    use super::check_redis_url;

    #[test]
    fn redis_provider_requires_a_present_parseable_url() {
        // A component that isn't on redis never looks at the URL.
        assert!(check_redis_url(false, "NOOK_QUEUE_PROVIDER", None).is_ok());
        assert!(check_redis_url(false, "NOOK_CACHE_PROVIDER", Some("nonsense")).is_ok());
        // redis: a missing URL refuses boot — for either component.
        assert!(check_redis_url(true, "NOOK_QUEUE_PROVIDER", None).is_err());
        assert!(check_redis_url(true, "NOOK_CACHE_PROVIDER", None).is_err());
        // redis: a MALFORMED URL refuses boot — never a silent fall-back.
        assert!(check_redis_url(true, "NOOK_QUEUE_PROVIDER", Some("not-a-redis-url")).is_err());
        assert!(check_redis_url(true, "NOOK_CACHE_PROVIDER", Some("not-a-redis-url")).is_err());
        // redis: a valid URL boots.
        assert!(check_redis_url(true, "NOOK_QUEUE_PROVIDER", Some("redis://redis:6379")).is_ok());
        assert!(check_redis_url(true, "NOOK_CACHE_PROVIDER", Some("redis://redis:6379")).is_ok());
    }
}

#[cfg(test)]
mod oidc_setup_tests {
    use super::{Config, OidcSetup};

    fn cfg(issuer: Option<&str>, client_id: Option<&str>, redirect: Option<&str>) -> Config {
        Config {
            oidc_issuer_url: issuer.map(Into::into),
            oidc_client_id: client_id.map(Into::into),
            oidc_redirect_url: redirect.map(Into::into),
            ..Config::for_test()
        }
    }

    /// MAIN-527 AC-1: an issuer with the rest of the set incomplete is an
    /// operator mid-configuration, so boot warns and names what is missing —
    /// where it previously fell through to the local-install INFO.
    #[test]
    fn a_partly_configured_provider_is_partial_and_names_what_is_missing() {
        assert_eq!(
            cfg(Some("https://idp.example"), Some("id"), None).oidc_setup(),
            OidcSetup::Partial {
                issuer: "https://idp.example",
                missing: vec!["OIDC_REDIRECT_URL"],
            }
        );
        assert_eq!(
            cfg(Some("https://idp.example"), None, Some("https://app/cb")).oidc_setup(),
            OidcSetup::Partial {
                issuer: "https://idp.example",
                missing: vec!["OIDC_CLIENT_ID"],
            }
        );
        assert_eq!(
            cfg(Some("https://idp.example"), None, None).oidc_setup(),
            OidcSetup::Partial {
                issuer: "https://idp.example",
                missing: vec!["OIDC_CLIENT_ID", "OIDC_REDIRECT_URL"],
            }
        );
    }

    /// MAIN-527 AC-2: no issuer at all stays the local case MAIN-397 made
    /// quiet. Half the point of AC-1 is that it does not reach this.
    #[test]
    fn no_issuer_at_all_is_the_local_case() {
        assert_eq!(cfg(None, None, None).oidc_setup(), OidcSetup::Absent);
        // Stray settings without an issuer are still no provider: nothing can
        // be discovered, and nobody misconfigures an issuer by omitting it.
        assert_eq!(
            cfg(None, Some("id"), Some("https://app/cb")).oidc_setup(),
            OidcSetup::Absent
        );
    }

    #[test]
    fn a_complete_set_is_configured_and_carries_the_issuer() {
        let full = cfg(
            Some("https://idp.example"),
            Some("id"),
            Some("https://app/cb"),
        );
        assert_eq!(
            full.oidc_setup(),
            OidcSetup::Configured {
                issuer: "https://idp.example"
            }
        );
        assert!(full.oidc_configured());
        assert!(!cfg(Some("https://idp.example"), Some("id"), None).oidc_configured());
        assert!(!cfg(None, None, None).oidc_configured());
    }
}
