//! Turning answers into deployment files.
//!
//! Kept as pure functions — answers in, file contents out — because these are
//! the parts of an installer whose breakage is silent. A compose file that
//! points at `latest` still starts. An `.env` that kept the example's
//! placeholder secret still boots, serves traffic, and signs sessions with a
//! key that is published on GitHub. Nothing goes wrong until it matters, so the
//! tests below assert on the generated text rather than on "did it run".

use std::fmt::Write as _;

/// How the control plane will be run.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Deployment {
    /// Compose, ports published directly.
    Compose,
    /// Compose behind an existing Traefik.
    ComposeTraefik,
    /// Print `docker run` lines for someone orchestrating elsewhere.
    DockerRun,
    /// The binary on the host, against a Postgres that already exists.
    Systemd,
}

/// Everything the generators need. Collected by the prompts, or by flags.
#[derive(Debug, Clone)]
pub struct ServerAnswers {
    /// e.g. `https://nook.example.com`
    pub public_url: String,
    /// Where nodes connect. Often a different name — see `agent_public_url`.
    pub agent_url: String,
    pub deployment: Deployment,
    /// Pinned, never `latest`.
    pub version: String,
    /// `None` means "bring your own", which is the only option without compose.
    pub postgres_password: Option<String>,
    pub database_url: Option<String>,
    pub session_secret: String,
    pub secrets_key: String,
    pub mcp_token: String,
    pub oidc: Option<Oidc>,
    /// Sign-in with no identity provider. Refused in production by the control
    /// plane itself; offered here only so someone can look around first.
    pub dev_auth: bool,
    pub tenant_name: String,
}

#[derive(Debug, Clone)]
pub struct Oidc {
    pub issuer_url: String,
    pub client_id: String,
    pub client_secret: String,
}

impl ServerAnswers {
    /// The hostname a Traefik router should match, derived from the URL.
    pub fn host_of(url: &str) -> String {
        url.trim_end_matches('/')
            .trim_start_matches("https://")
            .trim_start_matches("http://")
            .split('/')
            .next()
            .unwrap_or("")
            .split(':')
            .next()
            .unwrap_or("")
            .to_string()
    }

    pub fn api_host(&self) -> String {
        Self::host_of(&self.public_url)
    }

    pub fn agent_host(&self) -> String {
        Self::host_of(&self.agent_url)
    }
}

/// The `.env` the control plane reads. Written 0600 by the caller.
pub fn env_file(a: &ServerAnswers) -> String {
    let mut s = String::new();
    s.push_str("# NookOS control plane — generated by `nook server init`.\n");
    s.push_str("# Secrets here are unique to this deployment. Back it up; do not commit it.\n\n");

    // `APP_ENV` and `AUTH_DEV_MODE` are not independent: the control plane
    // refuses to start when dev sign-in is enabled in production, and rightly
    // so. Emitting the combination anyway would ship an installer whose output
    // does not boot — which is exactly what happened the first time this ran.
    s.push_str(if a.dev_auth {
        "APP_ENV=dev\n"
    } else {
        "APP_ENV=production\n"
    });
    s.push_str("CONTROL_PLANE_BIND=0.0.0.0:8080\n");
    let _ = writeln!(s, "PUBLIC_BASE_URL={}", a.public_url);
    let _ = writeln!(s, "WEB_ORIGIN={}", a.public_url);
    s.push_str("RUST_LOG=nook_control=info,nook=info\n\n");

    let db = a.database_url.clone().unwrap_or_else(|| {
        format!(
            "postgres://nook:{}@postgres:5432/nook",
            a.postgres_password.as_deref().unwrap_or("nook")
        )
    });
    let _ = writeln!(s, "DATABASE_URL={db}");
    if let Some(pw) = &a.postgres_password {
        let _ = writeln!(s, "POSTGRES_PASSWORD={pw}");
    }
    s.push('\n');

    s.push_str("# Sessions are signed with this. Rotating it signs everyone out.\n");
    let _ = writeln!(s, "SESSION_SECRET={}", a.session_secret);
    s.push_str("SESSION_TTL_HOURS=168\n");
    s.push_str("# At-rest encryption for stored secrets. LOSING THIS LOSES THEM.\n");
    let _ = writeln!(s, "SECRETS_KEY={}", a.secrets_key);
    let _ = writeln!(s, "MCP_TOKEN={}\n", a.mcp_token);

    match &a.oidc {
        Some(o) => {
            let _ = writeln!(s, "OIDC_ISSUER_URL={}", o.issuer_url);
            let _ = writeln!(s, "OIDC_CLIENT_ID={}", o.client_id);
            let _ = writeln!(s, "OIDC_CLIENT_SECRET={}", o.client_secret);
            let _ = writeln!(
                s,
                "OIDC_REDIRECT_URL={}/api/v1/auth/callback",
                a.public_url.trim_end_matches('/')
            );
            s.push_str("OIDC_SCOPES=\"openid profile email\"\n");
        }
        None => {
            s.push_str("# No identity provider configured yet. Fill these in and restart.\n");
            s.push_str("OIDC_ISSUER_URL=\nOIDC_CLIENT_ID=\nOIDC_CLIENT_SECRET=\n");
            let _ = writeln!(
                s,
                "OIDC_REDIRECT_URL={}/api/v1/auth/callback",
                a.public_url.trim_end_matches('/')
            );
            s.push_str("OIDC_SCOPES=\"openid profile email\"\n");
        }
    }
    if a.dev_auth {
        s.push_str("\n# Sign in without an identity provider, for evaluation. APP_ENV is dev\n");
        s.push_str("# above BECAUSE of this: the control plane refuses to start with dev\n");
        s.push_str("# sign-in enabled in production. Configure OIDC, delete this line, and\n");
        s.push_str("# set APP_ENV=production before anyone else can reach it.\n");
        s.push_str("AUTH_DEV_MODE=true\n");
    }
    s.push('\n');
    let _ = writeln!(s, "DEFAULT_TENANT_NAME={}", a.tenant_name);

    s.push_str("\n# The agent listener terminates TLS in-process (only it knows which\n");
    s.push_str("# tenant's CA to judge a client certificate against), so it does not sit\n");
    s.push_str("# behind the proxy that fronts the API.\n");
    s.push_str("NOOK_AGENT_BIND=0.0.0.0:8081\n");
    s.push_str("NOOK_AGENT_TLS_CERT=/etc/nook/agent.crt\n");
    s.push_str("NOOK_AGENT_TLS_KEY=/etc/nook/agent.key\n");
    let _ = writeln!(s, "NOOK_AGENT_PUBLIC_URL={}", a.agent_url);
    s
}

/// `docker-compose.yml`.
pub fn compose_file(a: &ServerAnswers) -> String {
    let traefik = a.deployment == Deployment::ComposeTraefik;
    let v = &a.version;
    let mut s = String::new();

    s.push_str("# NookOS control plane — generated by `nook server init`.\n");
    s.push_str("#\n# Image tags are pinned. `latest` would make an unrelated `docker compose\n");
    s.push_str("# up` a surprise upgrade, and a rollback an archaeology exercise.\n\n");

    if traefik {
        s.push_str("networks:\n  traefik_default:\n    external: true\n  internal:\n\n");
    }

    s.push_str("services:\n");

    // ---- postgres
    s.push_str("  postgres:\n    image: postgres:16-alpine\n    restart: unless-stopped\n");
    s.push_str("    environment:\n      POSTGRES_USER: nook\n");
    s.push_str("      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}\n      POSTGRES_DB: nook\n");
    s.push_str("    volumes:\n      - pgdata:/var/lib/postgresql/data\n");
    if traefik {
        s.push_str("    networks: [internal]\n");
    }
    s.push_str("    healthcheck:\n      test: [\"CMD-SHELL\", \"pg_isready -U nook\"]\n");
    s.push_str("      interval: 5s\n      timeout: 5s\n      retries: 30\n\n");

    // ---- control plane
    let _ = writeln!(
        s,
        "  control-plane:\n    image: ghcr.io/nook-os/nook-control:{v}"
    );
    s.push_str("    restart: unless-stopped\n    env_file: .env\n");
    s.push_str(
        "    volumes:\n      # The agent listener's certificate. Nodes pin its fingerprint.\n",
    );
    s.push_str("      - ./agent-certs:/etc/nook:ro\n");
    s.push_str("    depends_on:\n      postgres:\n        condition: service_healthy\n");
    if traefik {
        s.push_str("    expose: [\"8080\"]\n");
        s.push_str("    networks:\n      internal:\n      traefik_default:\n");
        s.push_str("    labels:\n");
        s.push_str("      - \"traefik.enable=true\"\n");
        s.push_str("      - \"traefik.docker.network=traefik_default\"\n");
        let _ = writeln!(
            s,
            "      - \"traefik.http.routers.nook-api.rule=Host(`{}`) && (PathPrefix(`/api`) || PathPrefix(`/mcp`) || PathPrefix(`/healthz`) || PathPrefix(`/.well-known`) || Path(`/install.sh`))\"",
            a.api_host()
        );
        s.push_str("      - \"traefik.http.routers.nook-api.entrypoints=websecure\"\n");
        s.push_str("      - \"traefik.http.routers.nook-api.tls=true\"\n");
        s.push_str("      - \"traefik.http.routers.nook-api.priority=20\"\n");
        s.push_str("      - \"traefik.http.services.nook-api.loadbalancer.server.port=8080\"\n");
        s.push_str("      # Nodes, by SNI, in PASSTHROUGH mode. This is load-bearing: the\n");
        s.push_str("      # control plane must see the client certificate itself, so the proxy\n");
        s.push_str("      # may route this stream but must never open it. Terminating here\n");
        s.push_str("      # breaks mutual TLS and the fingerprint pin in one go.\n");
        let _ = writeln!(
            s,
            "      - \"traefik.tcp.routers.nook-agent.rule=HostSNI(`{}`)\"",
            a.agent_host()
        );
        s.push_str("      - \"traefik.tcp.routers.nook-agent.entrypoints=websecure\"\n");
        s.push_str("      - \"traefik.tcp.routers.nook-agent.tls.passthrough=true\"\n");
        s.push_str("      - \"traefik.tcp.services.nook-agent.loadbalancer.server.port=8081\"\n");
    } else {
        s.push_str("    ports:\n      - \"8080:8080\"\n      - \"8081:8081\"\n");
    }
    s.push('\n');

    // ---- web
    let _ = writeln!(s, "  web:\n    image: ghcr.io/nook-os/nook-web:{v}");
    s.push_str("    restart: unless-stopped\n");
    s.push_str("    environment:\n      CONTROL_PLANE_ORIGIN: http://control-plane:8080\n");
    s.push_str("    depends_on: [control-plane]\n");
    if traefik {
        s.push_str(
            "    expose: [\"80\"]\n    networks:\n      internal:\n      traefik_default:\n",
        );
        s.push_str("    labels:\n      - \"traefik.enable=true\"\n");
        s.push_str("      - \"traefik.docker.network=traefik_default\"\n");
        let _ = writeln!(
            s,
            "      - \"traefik.http.routers.nook-web.rule=Host(`{}`)\"",
            a.api_host()
        );
        s.push_str("      - \"traefik.http.routers.nook-web.entrypoints=websecure\"\n");
        s.push_str("      - \"traefik.http.routers.nook-web.tls=true\"\n");
        s.push_str("      - \"traefik.http.routers.nook-web.priority=10\"\n");
        s.push_str("      - \"traefik.http.services.nook-web.loadbalancer.server.port=80\"\n");
    } else {
        s.push_str("    ports:\n      - \"80:80\"\n");
    }

    s.push_str("\nvolumes:\n  pgdata:\n");
    s
}

/// `docker run` lines, for someone whose orchestration lives elsewhere.
pub fn docker_run_script(a: &ServerAnswers) -> String {
    let mut s = String::new();
    s.push_str("# NookOS control plane, without compose.\n");
    s.push_str("# Bring your own Postgres; DATABASE_URL is in .env.\n\n");
    s.push_str("docker network create nook 2>/dev/null || true\n\n");
    let _ = writeln!(
        s,
        "docker run -d --name nook-control --network nook --restart unless-stopped \\\n  \
           --env-file .env \\\n  \
           -v \"$PWD/agent-certs:/etc/nook:ro\" \\\n  \
           -p 8080:8080 -p 8081:8081 \\\n  \
           ghcr.io/nook-os/nook-control:{}\n",
        a.version
    );
    let _ = writeln!(
        s,
        "docker run -d --name nook-web --network nook --restart unless-stopped \\\n  \
           -e CONTROL_PLANE_ORIGIN=http://nook-control:8080 \\\n  \
           -p 80:80 \\\n  \
           ghcr.io/nook-os/nook-web:{}",
        a.version
    );
    s
}

/// The systemd unit for a node agent.
///
/// `user` selects `systemctl --user` (no `User=`, since the manager already
/// runs as that person) versus a system unit.
pub fn node_unit(user_mode: bool, exec: &str, home: &str, unix_user: &str) -> String {
    let mut s = String::new();
    s.push_str("# NookOS node agent — generated by `nook setup`.\n\n");
    s.push_str("[Unit]\nDescription=NookOS node agent\n");
    if user_mode {
        s.push_str("After=network-online.target\n\n");
    } else {
        s.push_str("After=network-online.target\nWants=network-online.target\n\n");
    }
    s.push_str("[Service]\nType=simple\n");
    if !user_mode {
        let _ = writeln!(s, "User={unix_user}\nGroup={unix_user}");
    }
    let _ = writeln!(s, "ExecStart={exec} run");
    s.push_str("Restart=always\nRestartSec=5\n");
    s.push_str("Environment=RUST_LOG=nook=info\n");
    let _ = writeln!(s, "Environment=HOME={home}\nWorkingDirectory={home}");
    s.push_str("\n# THE important line. tmux is the buffer of record: sessions are meant to\n");
    s.push_str("# survive the agent restarting, and `Restart=always` means it will restart —\n");
    s.push_str("# on a network blip, a control-plane deploy, a crash. systemd's default\n");
    s.push_str("# KillMode kills the whole control group, which includes the tmux server the\n");
    s.push_str("# agent started, so every one of those restarts would silently take the\n");
    s.push_str("# user's terminals with it. Stop the agent only; leave its tmux alone.\n");
    s.push_str("KillMode=process\n");
    if !user_mode {
        s.push_str(
            "\n# The node's whole job is spawning dev tooling — keep hardening light but real.\n",
        );
        s.push_str("NoNewPrivileges=yes\nProtectSystem=full\n");
        let _ = writeln!(s, "ReadWritePaths={home} /tmp");
    }
    s.push_str("\n[Install]\n");
    s.push_str(if user_mode {
        "WantedBy=default.target\n"
    } else {
        "WantedBy=multi-user.target\n"
    });
    s
}

/// A supervisord program config.
///
/// Two lines carry the whole reason self-update is safe under supervisord, and
/// both are easy to get wrong:
///
/// - `autorestart=true`, NOT `unexpected`. Self-update exits 0 on purpose so
///   the supervisor restarts it into the new binary. supervisord treats exit 0
///   as a clean, EXPECTED stop, so under `autorestart=unexpected` — a common
///   default in examples — the node would simply stay down after every update.
/// - `stopasgroup`/`killasgroup` = false. The agent starts a tmux server that
///   holds the user's sessions, and those are meant to outlive an agent
///   restart. supervisord defaults these to false already; setting them makes
///   sure a future default change cannot quietly take the terminals down. This
///   is the same concern systemd's `KillMode=process` addresses.
pub fn node_supervisord_conf(exec: &str, home: &str, user: &str) -> String {
    format!(
        "# NookOS node agent — generated by `nook setup`.\n\
         [program:nook-node]\n\
         command={exec} run\n\
         directory={home}\n\
         user={user}\n\
         autostart=true\n\
         autorestart=true\n\
         startsecs=3\n\
         stopsignal=TERM\n\
         stopasgroup=false\n\
         killasgroup=false\n\
         environment=HOME=\"{home}\",RUST_LOG=\"nook=info\"\n\
         stdout_logfile=/var/log/nook-node.log\n\
         stderr_logfile=/var/log/nook-node.err.log\n"
    )
}

/// A launchd agent for macOS.
///
/// The equivalent of the systemd user unit: runs as the person, starts at
/// login, and restarts on its own. `KeepAlive` is the counterpart of
/// `Restart=always` — without it launchd starts the agent once and never
/// again, which looks identical to working right up until the first network
/// blip.
///
/// Unlike systemd there is no KillMode to worry about: launchd does not kill
/// the process group by default, so the tmux server survives a restart of the
/// agent without any special handling.
pub fn node_launchd_plist(exec: &str, home: &str, label: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{exec}</string>
    <string>run</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>{home}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>{home}</string>
    <key>RUST_LOG</key>
    <string>nook=info</string>
    <!-- launchd gives an agent a minimal PATH. The node spawns the person's
         own tooling, so it needs the paths a login shell would have —
         Homebrew on both Apple silicon and Intel, plus the usual. -->
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>StandardOutPath</key>
  <string>{home}/Library/Logs/nook-node.log</string>
  <key>StandardErrorPath</key>
  <string>{home}/Library/Logs/nook-node.log</string>
</dict>
</plist>
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Parse the way dotenvy will: assignments only, comments ignored.
    ///
    /// Asserting on `contains` treats prose in a comment as configuration,
    /// which is both a false alarm and, worse, capable of hiding a real one.
    fn settings(env: &str) -> std::collections::HashMap<String, String> {
        env.lines()
            .map(str::trim)
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .filter_map(|l| l.split_once('='))
            .map(|(k, v)| (k.to_string(), v.trim_matches('"').to_string()))
            .collect()
    }

    fn answers(deployment: Deployment) -> ServerAnswers {
        ServerAnswers {
            public_url: "https://nook.example.com".into(),
            agent_url: "https://agent.nook.example.com".into(),
            deployment,
            version: "v9.9.9".into(),
            postgres_password: Some("pg-secret".into()),
            database_url: None,
            session_secret: "s".repeat(64),
            secrets_key: "k".repeat(64),
            mcp_token: "m".repeat(32),
            oidc: None,
            dev_auth: false,
            tenant_name: "acme".into(),
        }
    }

    /// The placeholder in `.env.example` is sixty-four zeroes. Shipping that
    /// into a real deployment means every session cookie is forgeable by
    /// anyone who has read the repo — and nothing visibly breaks.
    #[test]
    fn secrets_are_generated_not_placeholders() {
        let cfg = settings(&env_file(&answers(Deployment::Compose)));
        assert_eq!(cfg["SESSION_SECRET"], "s".repeat(64));
        assert_eq!(cfg["SECRETS_KEY"], "k".repeat(64));
        assert_eq!(cfg["POSTGRES_PASSWORD"], "pg-secret");
        assert_ne!(
            cfg["SESSION_SECRET"],
            "0".repeat(64),
            "the .env.example placeholder"
        );
        // And the database URL must actually use that password, not the
        // default from the dev compose file.
        assert_eq!(
            cfg["DATABASE_URL"],
            "postgres://nook:pg-secret@postgres:5432/nook"
        );
    }

    /// A `latest` tag turns an unrelated `docker compose up` into a surprise
    /// upgrade, and there is no way to tell from the file what is running.
    #[test]
    fn images_are_pinned_never_latest() {
        for d in [Deployment::Compose, Deployment::ComposeTraefik] {
            let c = compose_file(&answers(d));
            assert!(c.contains("nook-control:v9.9.9"), "{d:?}");
            assert!(c.contains("nook-web:v9.9.9"), "{d:?}");
            assert!(!c.contains(":latest"), "{d:?} pinned to latest");
        }
        assert!(!docker_run_script(&answers(Deployment::DockerRun)).contains(":latest"));
    }

    /// The one that cost a live debugging session: a Traefik router that
    /// terminates TLS holds the client certificate and hands the control plane
    /// plaintext, so mutual auth silently stops being mutual.
    #[test]
    fn the_traefik_agent_router_passes_through() {
        let c = compose_file(&answers(Deployment::ComposeTraefik));
        assert!(c.contains("traefik.tcp.routers.nook-agent.tls.passthrough=true"));
        assert!(c.contains("HostSNI(`agent.nook.example.com`)"));
        assert!(c.contains("traefik.tcp.services.nook-agent.loadbalancer.server.port=8081"));
        // And it must NOT have been given a certificate resolver, which would
        // make Traefik terminate it after all.
        assert!(!c.contains("nook-agent.tls.certresolver"));
    }

    /// Without a proxy the ports have to be published, or nothing can reach
    /// either listener.
    #[test]
    fn plain_compose_publishes_both_ports() {
        let c = compose_file(&answers(Deployment::Compose));
        assert!(c.contains("\"8080:8080\""));
        assert!(c.contains("\"8081:8081\""));
        assert!(!c.contains("traefik.enable"));
    }

    #[test]
    fn hosts_are_derived_from_urls() {
        let a = answers(Deployment::ComposeTraefik);
        assert_eq!(a.api_host(), "nook.example.com");
        assert_eq!(a.agent_host(), "agent.nook.example.com");
        let mut b = a.clone();
        b.public_url = "http://box.local:8080/".into();
        assert_eq!(b.api_host(), "box.local", "port and path must be stripped");
    }

    #[test]
    fn oidc_redirect_is_built_from_the_public_url() {
        let mut a = answers(Deployment::Compose);
        a.public_url = "https://nook.example.com/".into();
        a.oidc = Some(Oidc {
            issuer_url: "https://auth.example.com".into(),
            client_id: "cid".into(),
            client_secret: "csec".into(),
        });
        // Exactly one slash — a doubled one is a redirect_uri mismatch at the
        // identity provider, which reads as "login is broken".
        let cfg = settings(&env_file(&a));
        assert_eq!(
            cfg["OIDC_REDIRECT_URL"],
            "https://nook.example.com/api/v1/auth/callback"
        );
    }

    /// launchd starts a job once unless told otherwise. Without KeepAlive the
    /// agent runs until the first disconnect and then quietly stays dead.
    #[test]
    fn the_launchd_agent_restarts_itself() {
        let p = node_launchd_plist("/Users/x/.local/bin/nook", "/Users/x", "dev.nookos.node");
        assert!(p.contains("<key>KeepAlive</key>"));
        assert!(p.contains("<key>RunAtLoad</key>"));
        // The node spawns the user's tooling; a minimal PATH breaks every
        // runtime that lives in Homebrew.
        assert!(
            p.contains("/opt/homebrew/bin"),
            "Apple silicon Homebrew missing"
        );
        assert!(p.contains("/usr/local/bin"), "Intel Homebrew missing");
    }

    /// Losing this is losing every terminal the user had open.
    #[test]
    fn both_unit_variants_keep_tmux_alive() {
        for user_mode in [true, false] {
            let u = node_unit(user_mode, "/home/x/.local/bin/nook", "/home/x", "x");
            assert!(u.contains("KillMode=process"), "user_mode={user_mode}");
        }
    }

    /// The two lines that make self-update safe under supervisord, asserted so
    /// they cannot be edited away. `autorestart=true` (a bare `exit 0` from a
    /// self-update must trigger a restart, which `unexpected` would not), and
    /// the group-kill flags off (so restarting the agent never reaps the tmux
    /// server holding the user's sessions).
    #[test]
    fn supervisord_conf_restarts_and_spares_tmux() {
        let c = node_supervisord_conf("/home/x/.local/bin/nook", "/home/x", "x");
        assert!(c.contains("autorestart=true"), "{c}");
        assert!(
            !c.contains("autorestart=unexpected"),
            "exit 0 from self-update must restart, which `unexpected` refuses"
        );
        assert!(c.contains("stopasgroup=false"), "{c}");
        assert!(c.contains("killasgroup=false"), "{c}");
        assert!(c.contains("command=/home/x/.local/bin/nook run"), "{c}");
        assert!(c.contains("[program:nook-node]"), "{c}");
    }

    /// A user unit that declares `User=` fails to start: the user manager is
    /// already that person and cannot switch.
    #[test]
    fn a_user_unit_does_not_set_user() {
        let u = node_unit(true, "/home/x/.local/bin/nook", "/home/x", "x");
        assert!(!u.contains("User="));
        assert!(u.contains("WantedBy=default.target"));

        let s = node_unit(false, "/home/x/.local/bin/nook", "/home/x", "x");
        assert!(s.contains("User=x"));
        assert!(s.contains("WantedBy=multi-user.target"));
    }

    /// `AUTH_DEV_MODE` only appears when asked for. The control plane refuses
    /// to boot with it under production, so emitting it by default would ship
    /// an installer whose output does not start.
    #[test]
    fn dev_auth_is_opt_in() {
        assert_eq!(
            settings(&env_file(&answers(Deployment::Compose))).get("AUTH_DEV_MODE"),
            None
        );
        let mut a = answers(Deployment::Compose);
        a.dev_auth = true;
        assert_eq!(settings(&env_file(&a))["AUTH_DEV_MODE"], "true");
    }

    /// The generated deployment has to actually start.
    ///
    /// `config.rs` bails with "AUTH_DEV_MODE must not be enabled when
    /// APP_ENV=production", so emitting both is an installer that writes a
    /// stack which crash-loops. The first real run of this wizard did exactly
    /// that; the assertion the earlier test was missing is this one.
    #[test]
    fn dev_auth_and_production_are_never_emitted_together() {
        let mut a = answers(Deployment::Compose);
        a.dev_auth = true;
        let cfg = settings(&env_file(&a));
        assert_eq!(cfg.get("APP_ENV").map(String::as_str), Some("dev"));
        assert_eq!(cfg.get("AUTH_DEV_MODE").map(String::as_str), Some("true"));

        a.dev_auth = false;
        let cfg = settings(&env_file(&a));
        assert_eq!(cfg.get("APP_ENV").map(String::as_str), Some("production"));
        assert_eq!(cfg.get("AUTH_DEV_MODE"), None);
    }

    /// Nodes are told where the agent listener is, which is not always where
    /// the API is.
    #[test]
    fn the_agent_url_is_recorded_for_joining_nodes() {
        let cfg = settings(&env_file(&answers(Deployment::Compose)));
        assert_eq!(
            cfg["NOOK_AGENT_PUBLIC_URL"],
            "https://agent.nook.example.com"
        );
    }
}

#[cfg(test)]
mod plist_dump {
    /// Writes the plist to `$NOOK_PLIST_OUT` so a real plist parser can check
    /// it — no Rust dependency here understands the format, and a malformed
    /// plist fails silently on macOS rather than loudly.
    ///
    ///   NOOK_PLIST_OUT=/tmp/n.plist cargo test -p nook-node dump_launchd_plist
    ///   python3 -c "import plistlib;print(plistlib.load(open('/tmp/n.plist','rb')))"
    ///
    /// Skipped unless the variable is set, so a normal run pays nothing.
    #[test]
    fn dump_launchd_plist() {
        if let Ok(path) = std::env::var("NOOK_PLIST_OUT") {
            let p = super::node_launchd_plist(
                "/Users/ryan/.local/bin/nook",
                "/Users/ryan",
                "dev.nookos.node",
            );
            std::fs::write(path, p).expect("write plist");
        }
    }
}
